version: 2
updates:
  - package-ecosystem: "pip"
    directories:
      - "/merge-mp3-files"
      - "/remove-background-vocals"
    schedule:
      interval: "daily"
  - package-ecosystem: "uv"
    directories:
      - "/convert-flac-to-mp3"
    schedule:
      interval: "daily"
